name: Checks

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  filenames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: |
          find . -mindepth 1 ! -regex '.*/[#@A-Za-z0-9._-]*' -print0 \
            | xargs -0 -I{} bash -c \
              'printf "::error file=%q::This filename contains undesired characters\n" "$1" && false' _ {}
  tests_osv-go:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Run `bindings/go` unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bindings/go
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: stable
          check-latest: true

      - run: go test ./...
      - run: gofmt -s */**.go
      - run: git diff --exit-code
      - run: go mod tidy -diff
  tests_osv-linter:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Run `osv-linter` unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/osv-linter
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: stable
          check-latest: true

      - run: go test ./...
      - run: gofmt -s */**.go
      - run: git diff --exit-code
      - run: go mod tidy -diff

  ecosystem_lists:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Check ecosystem lists
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.13
      - run: python3 ./scripts/update-ecosystems-lists.py
      - run: |
          git diff --name-only \
            | xargs -I '{}' bash -c \
              'echo "::error file={},line=1::This needs to be regenerated by running \`python3 ./scripts/update-ecosystems-lists.py\`" && false'

  validate_schema_databases_table:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Ensure schema databases table is valid
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.13
      - run: python3 ./scripts/validate-schema-table.py

  validate-osv-schema:
    name: Validate OSV Schema
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate OSV Schema
        uses: dsanders11/json-schema-validate-action@ec60131eddf6f51ed0c737fdcd28616ae1a0e564 # v1.2.0
        with:
          # https://github.com/marketplace/actions/json-schema-validate#validating-schema
          schema: json-schema
          files: validation/schema.json
